iawia002/Lulu

.travis.yml
Pipfile
Pipfile.lock
lulu/config.py
lulu/extractors/netease.py
lulu/version.py
setup.py
tests/download.py

fix #6 
referrer soimort/you-get#2552 and [spider163](https://github.com/Chengyumeng/spider163)

update netease music download

---

lulu/extractors/youku.py
lulu/version.py
tests/download.py

⬆️ youku ccode

---

lulu/extractor.py
lulu/extractors/netease.py
lulu/extractors/youku.py

#2 
ccode 参考自 soimort/you-get#2556 和 [[youku] update ccode](https://github.com/soimort/you-get/commit/219ac3ce62cbebf7a12882086d080d184248d625)

更新优酷下载器，使用多个 ccode 尝试下载

---

lulu/extractors/bilibili.py
tests/download.py

extractors/bilibili: update code format and bangumi title format

---

lulu/extractors/bilibili.py
lulu/extractors/kuaishou.py
tests/download.py

 extractors/kuaishou: rebuild and add some tests

---

lulu/common.py
lulu/extractors/acfun.py
lulu/extractors/embed.py
lulu/extractors/fantasy.py
lulu/extractors/huaban.py
lulu/extractors/tumblr.py
lulu/extractors/vine.py
tests/download.py

 extractors: code format

---

lulu/extractors/instagram.py
tests/download.py

extractors/instagram: rewrite and add some tests

---

lulu/extractors/imgur.py

extractors/imgur: code format

---

lulu/extractors/youtube.py
tests/test_extractors.py

extractors/youtube: code format

---

lulu/extractors/ixigua.py
tests/test_extractors.py

extractors/ixigua: code format and add some tests

---

README.md
lulu/extractors/douban.py
tests/test_extractors.py

extractors/douban: code format and add support for movie trailer playlist

---

lulu/extractors/douyutv.py
tests/test_extractors.py

extractors/douyutv: code format

---

lulu/extractors/zhanqi.py
lulu/version.py
tests/test_extractors.py

extractors/zhanqi: code format, 0.3.0

---

lulu/common.py
lulu/extractor.py
lulu/extractors/iqiyi.py
lulu/processor/ffmpeg.py

extractors: remove iqiyi 'dirty hack', fix ffmpeg params for iqiyi

---

lulu/extractor.py
lulu/extractors/bilibili.py
lulu/extractors/iqiyi.py

extractors/iqiyi: fix m3u8 url

---

lulu/extractor.py
lulu/extractors/iqiyi.py

referrer #44 
referrer #48 
fix #53

extractors/iqiyi: Use download_urls to download instead of ffmpeg

---

lulu/common.py
lulu/extractors/google.py
lulu/extractors/ifeng.py
lulu/extractors/mtv81.py
lulu/extractors/qq_egame.py
lulu/extractors/theplatform.py
lulu/extractors/twitter.py
lulu/extractors/universal.py
lulu/extractors/youtube.py
lulu/util/strings.py

common: replace unescape_html with unescape

---

lulu/extractors/mgtv.py

extractors/mgtv: remove download hack

---

lulu/processor/join_flv.py
lulu/processor/join_ts.py
lulu/processor/rtmpdump.py
lulu/util/log.py
lulu/util/term.py

*: code format

---

README.md
lulu/common.py
lulu/extractor.py
lulu/extractors/mgtv.py

common: experimental multi-threaded download

---

lulu/common.py

common: fix a merge issue when using multi-threaded download

---

lulu/common.py
lulu/extractor.py

common: launch_player now supports http headers(mpv only)

---

lulu/common.py

common: disable ssl verify

---

lulu/common.py

1.fix iOS python3.6 crash sys.stout.buffer
2.fix has no ffmpeg merge extenstion mp4 file failed. mp4 real is flv or ts. for example youku is real flv, twitter is real ts

iOS Pythonista run Lulu. need not  sys.stout.buffer and no ffmpeg. so found Youku and twitter merge failed. now is fixed.and download merge perfect.
